name: House-Keeping Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "requirements*.txt"
      - "setup.*"
      - "src/**/*"
      - "tests/*.py"
      - "docs/**/*"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install test dependencies
        run: python -m pip install tox
      - name: Run flake8
        run: |
          tox -e flake8

  docs:
    name: Test documentation builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install test dependencies
        run: python -m pip install tox
      - name: Test
        run: python -m tox -e docs
