name: MS Windows Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "requirements*.txt"
      - "setup.*"
      - "src/**/*"
      - "tests/*.py"

jobs:
  windows-legacy-tests:
    name: Python ${{ matrix.python }} on (legacy) ${{ matrix.os }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "pypy-3.7"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install tox
      - name: Test
        run: python -m tox -e py

  windows-tests:
    name: Python ${{ matrix.python }} on ${{ matrix.os }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "pypy-3.7"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install tox
      - name: Test
        run: python -m tox -e py
